---
services:
  db:
    image: postgres:17-alpine
    env_file: [.env]
    ports: [5432:5432]
    volumes: [./local/postgres/data:/var/lib/postgresql/data]
  analytics-db:
    image: influxdb:2-alpine
    env_file: [.env]
    ports: [8086:8086]
    volumes:
      - ./local/influxdb/data:/var/lib/influxdb2
      - ./local/influxdb/config:/etc/influxdb2
  cache:
    image: valkey/valkey:8.1.1-alpine
    env_file: [.env]
    ports: [6379:6379]
    volumes: [./local/valkey/data:/data]
